project_id = "wrbsknjrlacdemgtqoyh"

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.notification-scheduler]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.export-user-data]
verify_jwt = true
